### ISSUE TITLE
<urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by milaogou** [svenschultze/Lidar-Localization-DL#1]
![image](https://github.com/svenschultze/Lidar-Localization-DL/assets/130544843/db172b05-aaaa-4c8d-a268-0510cb8dc70b)
Can't connect to the server to load dataset, can anyone help?

**Comment by svenschultze** [comment]
Hey, thanks for the issue!
The urls are outdated, I just uploaded the datasets here:
[https://huggingface.co/datasets/svenschultze/lidar-localization](https://huggingface.co/datasets/svenschultze/lidar-localization)

I updated the code accordingly, please let me know if it works now.
