### ISSUE TITLE
Issue with Loading Files in the Updated Dataset

### ISSUE THREAD

**Issue by milaogou** [svenschultze/Lidar-Localization-DL#3]
Dear svenschultze,

I hope this message finds you well. First and foremost, I would like to express my gratitude for your prompt response and the recent update of the dataset. Your efforts are greatly appreciated.

However, I have encountered an issue while trying to load specific files in the dataset. There are three instances where I am unable to load the files, as indicated below:

1.map = read_pgm("map.pgm")

2.model.load_weights("residual_gazebo.h5")

I understand that you have been very responsive in addressing issues in the dataset, and I am grateful for your continuous support. I am reporting these issues in the hope that you may be able to provide some guidance or assistance in resolving them.

Your dedication to maintaining and improving the dataset is highly valued. Please let me know if there is any additional information or logs that I can provide to assist you in identifying the root causes of these issues.

Thank you once again for your contributions to the community. Your work is making a significant impact, and I am looking forward to your insights and assistance on this matter.

Best regards,
Laogou Mi

![image](https://github.com/svenschultze/Lidar-Localization-DL/assets/130544843/fdb86d75-995d-4b6f-9015-63f5b1a5946a)
![image](https://github.com/svenschultze/Lidar-Localization-DL/assets/130544843/eb69bee7-2cd8-4b7a-bd4b-b27f25ccc837)
![image](https://github.com/svenschultze/Lidar-Localization-DL/assets/130544843/542a354f-43a9-4709-9fd2-1076c8fd91da)

**Comment by svenschultze** [comment]
Dear milaogou,

I have uploaded the missing files on huggingface and updated the notebooks accordingly.
I'm glad our work can be of help to you, may I ask out of curiosity what you are using it for?

Best regards,
Sven Schultze

**Comment by milaogou** [comment]
Dear Sven Schultze,

Thank you for your prompt response and for uploading the missing files on Hugging Face as well as updating the notebooks. We appreciate your efforts in making the project more accessible.

In response to your curiosity about our intended use, a friend of mine is looking to develop a multi-sensor fusion algorithm and has been researching relevant projects for inspiration. Your project appeared to align closely with their interests. However, they encountered issues with running the notebooks, which prompted my inquiry.

We are excited to explore the potential of your work, and any assistance in resolving the notebook issues would be greatly appreciated. Once again, thank you for your contributions and support.

Best regards,
Laogou Mi
